/* eslint-disable */
export default [
  [
    [
      { channel: 177, index: 73, type: 'button' },
      { channel: 177, index: 57, type: 'encoder' },
      { channel: 177, index: 89, type: 'knob' },
      { channel: 177, index: 97, type: 'knob' },
      { channel: 177, index: 8, type: 'button', command: 'toggleMute', track: 0 },
      { channel: 177, index: 24, type: 'button', command: 'toggleSolo', track: 0 },
      { channel: 177, index: 40, type: 'button', toggle: true },
      { channel: 177, index: 0, type: 'fader' },
    ],
    [
      { channel: 177, index: 74, type: 'button' },
      { channel: 177, index: 58, type: 'encoder' },
      { channel: 177, index: 90, type: 'knob' },
      { channel: 177, index: 98, type: 'knob' },
      { channel: 177, index: 9, type: 'button', command: 'toggleMute', track: 1 },
      { channel: 177, index: 25, type: 'button', command: 'toggleSolo', track: 1 },
      { channel: 177, index: 41, type: 'button' },
      { channel: 177, index: 1, type: 'fader' },
    ],
    [
      { channel: 177, index: 75, type: 'button' },
      { channel: 177, index: 59, type: 'encoder' },
      { channel: 177, index: 91, type: 'knob' },
      { channel: 177, index: 99, type: 'knob' },
      { channel: 177, index: 10, type: 'button', command: 'toggleMute', track: 2 },
      { channel: 177, index: 26, type: 'button', command: 'toggleSolo', track: 2 },
      { channel: 177, index: 42, type: 'button' },
      { channel: 177, index: 2, type: 'fader' },
    ],
    [
      { channel: 177, index: 76, type: 'button' },
      { channel: 177, index: 60, type: 'encoder' },
      { channel: 177, index: 92, type: 'knob' },
      { channel: 177, index: 100, type: 'knob' },
      { channel: 177, index: 11, type: 'button', command: 'toggleMute', track: 3 },
      { channel: 177, index: 27, type: 'button', command: 'toggleSolo', track: 3 },
      { channel: 177, index: 43, type: 'button' },
      { channel: 177, index: 3, type: 'fader' },
    ],
    [
      { channel: 177, index: 77, type: 'button' },
      { channel: 177, index: 61, type: 'encoder' },
      { channel: 177, index: 93, type: 'knob' },
      { channel: 177, index: 101, type: 'knob' },
      { channel: 177, index: 12, type: 'button', command: 'toggleMute', track: 4 },
      { channel: 177, index: 28, type: 'button', command: 'toggleSolo', track: 4 },
      { channel: 177, index: 44, type: 'button' },
      { channel: 177, index: 4, type: 'fader' },
    ],
    [
      { channel: 177, index: 78, type: 'button' },
      { channel: 177, index: 62, type: 'encoder' },
      { channel: 177, index: 94, type: 'knob' },
      { channel: 177, index: 102, type: 'knob' },
      { channel: 177, index: 13, type: 'button', command: 'toggleMute', track: 5 },
      { channel: 177, index: 29, type: 'button', command: 'toggleSolo', track: 5 },
      { channel: 177, index: 45, type: 'button' },
      { channel: 177, index: 5, type: 'fader' },
    ],
    [
      { channel: 177, index: 79, type: 'button' },
      { channel: 177, index: 63, type: 'encoder' },
      { channel: 177, index: 95, type: 'knob' },
      { channel: 177, index: 103, type: 'knob' },
      { channel: 177, index: 14, type: 'button', command: 'toggleMute', track: 6 },
      { channel: 177, index: 30, type: 'button', command: 'toggleSolo', track: 6 },
      { channel: 177, index: 46, type: 'button' },
      { channel: 177, index: 6, type: 'fader' },
    ],
    [
      { channel: 177, index: 80, type: 'button' },
      { channel: 177, index: 64, type: 'encoder' },
      { channel: 177, index: 96, type: 'knob' },
      { channel: 177, index: 104, type: 'knob' },
      { channel: 177, index: 15, type: 'button', command: 'toggleMute', track: 7 },
      { channel: 177, index: 31, type: 'button', command: 'toggleSolo', track: 7 },
      { channel: 177, index: 47, type: 'button' },
      { channel: 177, index: 7, type: 'fader' },
    ],
  ],
  [
    [
      { channel: 178, index: 57, type: 'encoder', command: 'setTrack' },
      { channel: 178, index: 8, type: 'button', command: 'toggleMute', track: 8 },
      { channel: 178, index: 24, type: 'button', command: 'scenePlay', scene: 0 },
    ],
    [
      { channel: 178, index: 58, type: 'encoder', command: 'setDevice' },
      { channel: 178, index: 8, type: 'button', command: 'toggleMute', track: 9 },
      { channel: 178, index: 25, type: 'button', command: 'scenePlay', scene: 1 },
    ],
    [
      { channel: 178, index: 26, type: 'button', command: 'scenePlay', scene: 2 },
    ],
    [
      { channel: 178, index: 27, type: 'button', command: 'scenePlay', scene: 3 },
    ],
    [
      { channel: 178, index: 28, type: 'button', command: 'scenePlay', scene: 4 },
    ],
    [
      { channel: 178, index: 29, type: 'button', command: 'scenePlay', scene: 5 },
    ],
    [
      { channel: 178, index: 30, type: 'button', command: 'scenePlay', scene: 6 },
    ],
    [
      { channel: 178, index: 31, type: 'button', command: 'scenePlay', scene: 7 },
    ],
    // [
    //   { channel: 178, index: 32, type: 'button', command: 'scenePlay', scene: 8 },
    // ],
  ],
  [[{ channel: 180, index: 113, type: 'button' },
    { channel: 180, index: 114, type: 'button' },
    { channel: 180, index: 115, type: 'button' },
    { channel: 180, index: 116, type: 'button' },
    { channel: 180, index: 117, type: 'button' },
    { channel: 180, index: 118, type: 'button' },
    { channel: 180, index: 119, type: 'button' },
    { channel: 180, index: 120, type: 'button' },
    { channel: 180, index: 121, type: 'button' },
    { channel: 180, index: 122, type: 'button' },
    { channel: 180, index: 123, type: 'button' },
    { channel: 180, index: 124, type: 'button' },
    { channel: 180, index: 125, type: 'button' },
    { channel: 180, index: 126, type: 'button' },
    { channel: 180, index: 127, type: 'button' },
    { channel: 179, index: 1, type: 'button' }]],
];
